[[news]]
date = "2026-09"
content = "Admitted to the Juris Master program (International Arbitration and Dispute Settlement) at Tsinghua University."

[[news]]
date = "2026-07"
content = "Lost a lot of money in the stock market 😭"

[[news]]
date = "2026-04"
content = "Won Second Prize & Best Advocate at the 18th Frankfurt Investment Arbitration Moot Court (FIAMC) National General Rounds 🏆"

[[news]]
date = "2025-01"
content = "Began a university-funded exchange program at the National University of Singapore."
