[[news]]
date = "2026-09"
content = "入读清华大学法律硕士项目（国际仲裁与争端解决方向）。"

[[news]]
date = "2026-04"
content = "在第十八届法兰克福投资仲裁模拟法庭（FIAMC）全国赛中获二等奖及最佳辩手 🏆"

[[news]]
date = "2025-01"
content = "赴新加坡国立大学参加校级资助交换项目。"
